### ISSUE TITLE
save model

### ISSUE THREAD

**Issue by Petite-chosse** [heytanay/pneumonia-detection#1]
How do we save the trained model?

**Comment by heytanay** [comment]
@Petite-chosse Generally you would do;
`model.save("model_name.h5py")`
You also need to install 
`pip install h5py`.

The reason I haven't saved the model is that I tried but it gave me a `Unicode Error`. I tried searching what it was but found nothing, so left it there.
You can try all the steps and then save the model. If it works, please do a PR!

**Comment by Petite-chosse** [comment]
Thank you! You are best.

**Comment by Petite-chosse** [comment]
Perhaps you should create a tf.train.Saver class to save the training model:
saver = tf.train.Saver ()

saver.save (sess, '. / model /')
Should not be used
model.save ('')
Of course this is just a guess from me, I did not try

**Comment by heytanay** [comment]
@Petite-chosse A few months ago, I revamped the Repository completely, this time I have saved a model too. You can download it if you want!
